config/routes.rb
Rails.application.routes.draw do

  get 'catering/index'
  get 'catering/menu'
  get 'catering/amenities'
  get 'catering/gallery'
  get 'catering/about'
  get 'catering/contact'
  get 'catering/packedmeal'
  get 'catering/cocktail'
  get 'catering/Register'
  get 'catering/login'

  resources :catering

  root 'catering#index'

end

app/models/catering.rb
class Catering < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catering_controller.rb
class CateringController < ApplicationController
  def index
  end

  def gallery
  end

  def menu
  end

  def Register

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catering_helper.rb
module CateringHelper
end

app/views/catering/cocktail.html.erb
<!--<div class="container">-->
<!--<div class="nav navbar-left contentmenu">-->
<!--<ul>-->
<!--<li  class="links"><a href="index.html">Latest Activity</a></li>-->
<!--<li  class="links"><a href="About.html">Profile</a></li>-->
<!--<li  class="links"><a href="Videos.html">Videos</a></li>-->
<!--<li  class="links"><a href="Images.html">Images</a></li>-->
<!--</ul>-->
<!--</div>-->
<!--</div>-->
<div class="container col-md-2">
  <div class="row contentmenu">
    <div class="col-md-10">
      <div class="tab-pane">

        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to 'Buffet Type', catering_menu_url %></li>
            <li><%= link_to 'Packed Meal', catering_packedmeal_url %></li>
            <li class="active"><a href="#" role="tab">Cocktail Type</a></li>
          </ul>
        </div>
        <!--<div class="menu_inclusions_col" id="#vtabs-content-c">-->
          <div class="menu_tab_panel">
            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="cocktail_type_title_div">COCKTAIL TYPE SERVICE</div>
                <div id="cocktail_type_title_short_desc">
                  Business meetings, company launching, event opening, VIP gatherings, and other functions may avail of our well-personalized customer cocktail party service.
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="cocktail_type_prices_div">
                  <div class="packed_meal_price_col">
                    <div class="menu_inclusions_title_div">
                      <span>Cocktail Php 190.00</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="main-course">
                  <div id="main_courses_row1">
                    <div id="col1">
                      <fieldset>
                        <div class="buffet_title">Menu A</div>
                        <div>
                          <ul>
                            <li>Chicken Roll with Ham & Butter</li>
                            <li>Shrimp Roll</li>
                            <li>Siomai</li>
                            <li>Lasagna</li>
                            <li>Bread</li>
                            <li>Peanuts</li>
                            <li>Fresh Fruits</li>
                            <li>Soft drinks or Juice</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col2">
                      <fieldset>
                        <div class="buffet_title">Menu B</div>
                        <div>
                          <ul>
                            <li>Pork Barbecue</li>
                            <li>Buttered Chicken</li>
                            <li>Cabbage Roll</li>
                            <li>Bam-I</li>
                            <li>Bread</li>
                            <li>Assorted Canafe</li>
                            <li>Dessert</li>
                            <li>Soft drinks or Juice</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="cocktail_type_prices_div">
                  <div class="packed_meal_price_col">
                    <div class="menu_inclusions_title_div">
                      <span>Cocktail Php 170.00</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="main-course">
                  <div id="main_courses_row1">
                    <div id="col1">
                      <fieldset>
                        <div class="buffet_title">Menu A</div>
                        <div>
                          <ul>
                            <li>Pork Embutido</li>
                            <li>Spaghetti</li>
                            <li>Empanada</li>
                            <li>Bread</li>
                            <li>Dessert</li>
                            <li>Soft drinks or Juice</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col2">
                      <fieldset>
                        <div class="buffet_title">Menu B</div>
                        <div>
                          <ul>
                            <li>Chicken Lollipop</li>
                            <li>Sotanghon Guisado</li>
                            <li>Fresh Lumpia</li>
                            <li>Bread</li>
                            <li>Fresh Fruits</li>
                            <li>Soft drinks or Juice</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span>Amenities</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="menu_inclusions_col">
                  <div class="inclusions_menu_div">
                    <fieldset>
                      <div id="col1">
                        <ul>
                          <li>One Free Buffet Tent</li>
                          <li>Uniformed Waiters</li>
                        </ul>
                      </div>
                      <div id="col2">
                        <ul>
                          <li>Simple Table Centerpieces</li>
                          <li>Cocktail Tables</li>
                        </ul>
                      </div>
                      <div id="col3">
                        <ul>
                          <li>Buffet Set-Up with Centerpieces</li>
                        </ul>
                      </div>
                    </fieldset>
                  </div>
                </div>
              </div>
            </div>


            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span>Optional Charges</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="inclusions_menu_div">
                    <fieldset>
                      <div id="col1">
                        <ul>
                          <li>Additional Tents</li>
                          <li>Ceiling Decors</li>
                          <li>Floral Arrangements</li>
                          <li>Red Carpet</li>
                        </ul>
                      </div>
                      <div id="col2">
                        <ul>
                          <li>Food Orders</li>
                          <li>Packed Meals</li>
                          <li>Kid's Tables and Chairs</li>
                        </ul>
                      </div>
                      <div id="col3">
                        <ul>
                          <li>Wine Glasses</li>
                          <li>Party Novelties</li>
                          <li>Cocktail Tables</li>
                        </ul>
                      </div>
                    </fieldset>
                  </div>
                </div>
              </div>
            </div>

          </div>
        <!--</div>-->
      </div>
    </div>
  </div>

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-4">
        <img src="/assets/logo.png" alt=#" style="width: 150px; height: 50px; margin-left: -40px; margin-top: 15px"/>
      </div>
      <div class="col-md-4 center-block">
        <p> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>
      </div>
      <div class="col-md-4">
        <img src="/assets/head.png" alt="" style="width: 150px; height: 50px; margin-left: 220px; margin-top: 15px"/>
      </div>
    </div>
  </div>
</div>

app/views/catering/index.html.erb
<div class="container">
    <div class="col-md-12 content1">
        <div class="carousel slide" id="samplecarousel" data-ride="carousel">
          <div class="carousel-inner center-block inner">
            <div class="item active">
              <img src="/assets/carousel images/caswedding.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casadding.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casfiesta.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casparty.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/cassocial_function.jpg"/>
            </div>
          </div>

        </div>
    </div>

<<<<<<< HEAD
=======

          <div class="clear slider1Image"></div>
        </ul>            	</div>
    </div>
>>>>>>> 7a76053b9650af1ad6b4429311d9b4e333e48932
      <div class="col-md-10 col-md-offset-1 content2">
        <div class="row">
          <div class="col-md-3">
            <img src="/assets/human1.png" class="port"/>
          </div>
          <div class="col-md-6">
            <p class="para">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Assumenda dolore ducimus magnam nisi quibusdam rem ut? Animi,
              beatae, consectetur dolorum ducimus exercitationem id ipsam molestias
              porro sequi tenetur veniam voluptatem!Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Assumenda dolore ducimus magnam nisi quibusdam rem ut? Animi,
              beatae, consectetur dolorum ducimus exercitationem id ipsam molestias
              porro sequi tenetur veniam voluptatem!
            </p>
          </div>
          <div class="col-md-3">
            <img src="/assets/lechon2.png" class="lechon"/>
          </div>
        </div>
        <hr style="border-color: #1f2124; width: 100%;"/>
        <h3>Catering Services</h3>
        <br/>
        <div class="row picture">
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/party.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/fiesta.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/adding.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/wedding.jpg" class="oct"/>
            </a>
          </div>
        </div>
        <div class="container">
          <div class="row service">
            <div class="col-md-3 ">
              <h4>Buffet Type</h4>
              <hr/>
              <h5>P230 / person</h5>
              <ul class="buffet">
                <li>5 Main Dishes</li>
                <li>1 Dessert</li>
                <li>1 Appetizer</li>
                <li>1 Round Softdrink</li>
                <li>Rice</li>
                <li>Purified Water</li>
              </ul>
            </div>
            <div class="col-md-3" >
              <h4>Packed Meal</h4>
              <hr/>
              <h6>Packed in a styrofoam, spoon, fork, and toothpick included.</h6>
              <ul class="packed">
                <li><h5>P130 / Person</h5></li>
                <li><h5>P120 / Person</h5></li>
                <li><h5>P110 / Person</h5></li>
              </ul>
            </div>
            <div class="col-md-3">
              <h4>Cocktail Type</h4>
              <hr/>
              <ul class="cocktail">
                <li><h5> P190 / Person</h5></li>
                <li><h5>P170 / Person</h5></li>
              </ul>
            </div>
            <div class="col-md-3">
              <h4>Our Amenities</h4>
              <hr/>
              <ul class="amenities">
                <li>Buffet Tent</li>
                <li>Tables and Chairs</li>
                <li>Skirted buffet table with centerpiece</li>
                <li>Uniformed Waiters</li>
              </ul>
            </div>
          </div>
          <div class="container ">
            <div class="row buttons">
              <div class="col-md-3">
<<<<<<< HEAD
                <button class="btn center-block"><%= link_to 'View Menu', catering_menu_path %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-info center-block"><%= link_to 'View Menu', catering_packedmeal_path %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-primary center-block"><%= link_to 'View Menu', catering_cocktail_path %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-danger center-block"><%= link_to 'More Info', catering_amenities_path %></button>
=======
                <button class="btn center-block"><%= link_to 'View Menu', catering_menu_url %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-info center-block"><%= link_to 'View Menu', catering_packedmeal_url %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-primary center-block"><%= link_to 'View Menu', catering_cocktail_url %></button>
              </div>
              <div class="col-md-3">
                <button class="btn btn-danger center-block"><%= link_to 'More Info', catering_amenities_url %></button>
>>>>>>> 7a76053b9650af1ad6b4429311d9b4e333e48932
              </div>
            </div>
          </div>
        </div>
      </div>
<<<<<<< HEAD
</div>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-4">
      <img src="/assets/logo.png" alt=#" style="width: 150px; height: 50px; margin-left: -40px; margin-top: 15px"/>
    </div>
    <div class="col-md-4 center-block">
      <p> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>
    </div>
    <div class="col-md-4">
      <img src="/assets/head.png" alt="" style="width: 150px; height: 50px; margin-left: 220px; margin-top: 15px"/>
    </div>
  </div>
</div>
=======

</div>
<!--<div class="container">-->
  <!--<div class="col-md-10 col-md-offset-1">-->
    <!--<div class="col-md-4">-->
      <!--<img src="/assets/logo.png" alt=#" style="width: 150px; height: 50px; margin-left: -40px; margin-top: 15px"/>-->
    <!--</div>-->
    <!--<div class="col-md-4 center-block">-->
      <!--<p> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>-->
    <!--</div>-->
    <!--<div class="col-md-4">-->
      <!--<img src="/assets/head.png" alt="" style="width: 150px; height: 50px; margin-left: 220px; margin-top: 15px"/>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
>>>>>>> 7a76053b9650af1ad6b4429311d9b4e333e48932
<script type="text/javascript" src="jquery-1.9.1.js"></script>
<script type="text/javascript" src="bootstrap.js"></script>
<script type="text/javascript">
    $(function(){
        $(".carousel").carousel({
<<<<<<< HEAD
            interval: 2000
        });
    });
</script>
=======
            interval: 3000
        });
    });
</script>

<!--&lt;!&ndash;<script type="text/javascript">&ndash;&gt;-->
<!--//    $(document).ready(function() {-->
<!--//        $('#slider1').s3Slider({-->
<!--//            timeOut: 3750-->
<!--//        });-->
<!--//    });-->
<!--//-->
<!--//    $(function() {-->
<!--//        $('#1990').lightBox();-->
<!--//    });-->
<!--</script>-->
>>>>>>> 7a76053b9650af1ad6b4429311d9b4e333e48932

app/views/catering/packedmeal.html.erb
<!--<div class="container">-->
<!--<div class="nav navbar-left contentmenu">-->
<!--<ul>-->
<!--<li  class="links"><a href="index.html">Latest Activity</a></li>-->
<!--<li  class="links"><a href="About.html">Profile</a></li>-->
<!--<li  class="links"><a href="Videos.html">Videos</a></li>-->
<!--<li  class="links"><a href="Images.html">Images</a></li>-->
<!--</ul>-->
<!--</div>-->
<!--</div>-->
<div class="container col-md-2">
  <div class="row contentmenu">
    <div class="col-md-10">
      <div class="tab-pane">

        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to 'Buffet Type', catering_menu_url %></li>
            <li class="active"><a href="#" role="tab" data-toggle="tab">Packed Meal</a></li>
            <li><%= link_to 'Cocktail Type', catering_cocktail_url %></li>
          </ul>
        </div>
        <!--<div class="menu_inclusions_col" id="#vtabs-content-b">-->
          <div class="menu_tab_panel">
            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div id="packed_meacl_type_title">PACKED MEAL</div>
                <div id="packed_meal_title_short_desc">
                  Packed in a styrofoam, spoon, fork, and toothpick included.
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="packed_meal_prices_div">
                  <div class="packed_meal_price_col">
                    <div class="packed_meal_price_title">Packed Menu Php 130.00</div>
                    <div>
                      <ul>
                        <li>3 Main Dishes</li>
                        <li>1 Dessert</li>
                        <li>2 cups rice</li>
                        <li>Juice in tetra pack</li>
                      </ul>
                    </div>
                  </div>

                  <div class="packed_meal_price_col">
                    <div class="packed_meal_price_title">Packed Menu Php 120.00</div>
                    <div>
                      <ul>
                        <li>2 Main Dishes</li>
                        <li>1 Dessert</li>
                        <li>2 cups rice</li>
                        <li>Juice in tetra pack</li>
                      </ul>
                    </div>
                  </div>

                  <div class="packed_meal_price_col">
                    <div class="packed_meal_price_title">Packed Menu Php 110.00</div>
                    <div>
                      <ul>
                        <li>2 Main Dishes</li>
                        <li>2 cups rice</li>
                        <li>Juice in tetra pack</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span>Main Dishes</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_short_desc_div">
                    Choose your main dishes here...
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div id="main-course">
                  <div id="main_courses_row1">
                    <div id="col1">
                      <fieldset>
                        <div class="buffet_title">PORK</div>
                        <div>
                          <ul>
                            <li>Pork Menudo</li>
                            <li>Pork Embutido</li>
                            <li>Sweet and Sour Pork</li>
                            <li>Braised Pork (Humba)</li>
                            <li>Breaded Pork Chop</li>
                            <li>Pork Steak</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col2">
                      <fieldset>
                        <div class="buffet_title">CHICKEN</div>
                        <div>
                          <ul>
                            <li>Chicken Chunk with Honey</li>
                            <li>Chicken Pandan</li>
                            <li>Chicken Pork Adobo</li>
                            <li>Buttered Chicken</li>
                            <li>Chicken Fillet w/ Sesame Seeds & Gravy</li>
                            <li>Chicken Roll w/ Ham &amp; Butter</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col3">
                      <fieldset>
                        <div class="buffet_title">SEAFOODS</div>
                        <div>
                          <ul>
                            <li>Sweet and Sour Fish</li>
                            <li>Fish Fillet with Corn Sauce</li>
                            <li>Fish Fillet with Chili Sauce</li>
                            <li>Steamed Fish Fillet w/ Ham & Black Mushroom</li>
                            <li>Fish Fillet with Tar-Tar Sauce</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                  </div>
                  <div id="main_courses_row2">
                    <div id="col1">
                      <fieldset>
                        <div class="buffet_title">BEEF</div>
                        <div>
                          <ul>
                            <li>Beef Steak</li>
                            <li>Beef with Onions</li>
                            <li>Stir Fry Beef</li>
                            <li>Beef Caldereta</li>
                            <li>Beef Tips in Oyster Sauce</li>
                            <li>Beef with Mushroom</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col2">
                      <fieldset>
                        <div class="buffet_title">NOODLES</div>
                        <div>
                          <ul>
                            <li>Spaghetti</li>
                            <li>Bam-I</li>
                            <li>Sotanghon Guisado</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                    <div id="col3">
                      <fieldset>
                        <div class="buffet_title">VEGGIES / OTHERS</div>
                        <div>
                          <ul>
                            <li>Shrimp Roll</li>
                            <li>Chao Pat Chin</li>
                            <li>Four Seasons Vegetables</li>
                          </ul>
                        </div>
                      </fieldset>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span>Dessert</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_short_desc_div">
                    Choose your mouthwatering dessert...
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="inclusions_menu_div">
                  <fieldset>
                    <div id="col1">
                      <ul>
                        <li>Fruit Salad</li>
                        <li>Shell Macaroni Salad</li>
                        <li>Macaroons</li>
                        <li>Brownies</li>
                      </ul>
                    </div>
                    <div id="col2">
                      <ul>
                        <li>Cassava Cake</li>
                        <li>Custard Cake</li>
                        <li>Chicken Macaroni</li>
                        <li>Maja Blanca</li>
                      </ul>
                    </div>
                    <div id="col3">
                      <ul>
                        <li>Cup Cake</li>
                        <li>Empanada</li>
                      </ul>
                    </div>
                  </fieldset>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="panel_hz_divider"></div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span>Rice</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="menu_inclusions_row">
              <div class="menu_inclusions_col">
                <div class="inclusions_menu_div">
                  <fieldset>
                    <div id="col1">
                      <ul>
                        <li>Plain Rice</li>
                      </ul>
                    </div>
                  </fieldset>
                </div>
              </div>
            </div>
          </div>
        <!--</div>-->
      </div>
    </div>
  </div>

  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-4">
        <img src="/assets/logo.png" alt=#" style="width: 150px; height: 50px; margin-left: -40px; margin-top: 15px"/>
      </div>
      <div class="col-md-4 center-block">
        <p> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>
      </div>
      <div class="col-md-4">
        <img src="/assets/head.png" alt="" style="width: 150px; height: 50px; margin-left: 220px; margin-top: 15px"/>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineCatering</title>
  <link rel="Shortcut Icon" href="/assets/ico.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all','data-turbolinks-track' => true%>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse"
            data-target="#NavbarToggle">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
          <a href="#" class="navbar-brand"
            data-toggle="tooltip"
            data-placement="right"
            title="Infinity Online Catering Services!">
            <img src="/assets/logo.png" alt="images" class="logo"/>
          </a>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="NavbarToggle">
        <ul class="nav navbar-nav">
          <li class="navborder"><%= link_to 'Home', catering_index_path %></li>
          <li class="navborder"><%= link_to 'Menu',catering_menu_path %></li>
          <li class="navborder"><%= link_to 'Amenities',catering_amenities_path %></li>
          <li class="navborder"><%= link_to 'Gallery', catering_gallery_path %></li>
          <li class="navborder"><%= link_to 'About us', catering_about_path %></li>
          <li class="navborder"><%= link_to 'Contact us', catering_contact_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <li class="navborder"><%= link_to 'Register', catering_Register_url %></li>
          <li class="navborder"><%= link_to 'Login', catering_login_url %></li>
        </ul>
      </div>

    </nav>

<%= yield %>

</body>
</html>